{
	title: 'Csakis Festival!',
	greeting: 'Welcome!',
	subtitle: 'We love Jesus!',
	section_one_title: 'Családos vasárnap havonta',
	section_one_body_text: 'Másfél évvel ezelött indítottuk a Családos Vasárnapot az Oroszfalvi templomban. Minden hónap végèn kerül sor ez alkalomra, amely mindenkinek szòl, felekezetre való tekintet nèlkül jönnek a házaspàrok, illetve családok a 12 órától kezdödö eseményre. Mi is történik ilyenkor? Dicsöítès, köszöntés, ima, majd a tanítás következik. (ezt házaspárok tartják, lehetöség van a szolgálatra, aki erre elhívàst érez)Elcsendesedés után ismèt énekelünk és szeretetvendégséggel zárjuk az összejövetelt. A gyermekekkel vasárnapi iskolás oktatók foglalkoznak. Szeretettel várunk alkalmainkra minden házaspárt, csalàdot, aki ùgy érzi, van még mit tanulnia Istentöl, testvéreinken keresztül.',
	section_two_title: 'Hol vagyunk',
	section_two_body_text: 'itt vagyunk. google map link itt van.',
	section_three_title: 'Magunkrol',
	section_three_body_text: 'A Kézdivásárhelyi Családos Keresztény Fesztivállal egy nyári pihenési és töltekezési lehetőséget szeretnénk biztosítani a családoknak. Mivel a családok nyaranta rengeteg kikapcsolódási lehetőség közül válogathatnak, ezért a mi fesztiválunk programja és légköre kimondottan keresztény lesz. Kirándulási, kikapcsolódási, töltekezési és sportolási lehetőségek mellett a házasságot érintő gondolatébresztőkön, előadásokon, életút beszélgetéseken vehetnek részt a fesztiválra látogatók. Természetesen a fesztiválok elvárásainak eleget téve koncertekre is sor kerül, de dicsőítésre, példaértékű családokkal fórumbeszélgetésekre, élményszínházra és egyéb alternatív programokra is sor kerül a rendezvényen. Mivel a család egészének kínálunk programot, ezért a gyerekek, ifjak részére külön programot is szervezünk, ahol ki-ki a korosztályának megfelelő tevékenységekbe kapcsolódhat be.',
	section_three_map_link: 'http://google.com',
	$section_one_body_text_type: 'textarea',
	section_one_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554035/sample.jpg',
	$section_one_image_type: 'image',
	section_two_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554035/sample.jpg',
	$section_two_image_type: 'image',
	section_three_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554035/sample.jpg',
	$section_three_image_type: 'image',
	section_four_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554035/sample.jpg',
	$section_four_image_type: 'image',
	$banner_image_type: 'image',
	banner_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/c_scale,w_1371/v1491554140/CSAKISbannerlong-withdates_u1k9ml.jpg',
	$logo_type: 'image',
	logo: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554139/CSAKISsquareTRANSPARENTjustlogo_f90dn3.png'
}
